In [32]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets


In [33]:
iris=datasets.load_iris()
x_values=iris.data[:,0]
print(x_values)


[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


In [34]:
y=iris.target 
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [35]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [36]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [37]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [38]:
print(x.shape)
x=x_values.reshape(150,1)
print(x)

(150, 1)
[[5.1]
 [4.9]
 [4.7]
 [4.6]
 [5. ]
 [5.4]
 [4.6]
 [5. ]
 [4.4]
 [4.9]
 [5.4]
 [4.8]
 [4.8]
 [4.3]
 [5.8]
 [5.7]
 [5.4]
 [5.1]
 [5.7]
 [5.1]
 [5.4]
 [5.1]
 [4.6]
 [5.1]
 [4.8]
 [5. ]
 [5. ]
 [5.2]
 [5.2]
 [4.7]
 [4.8]
 [5.4]
 [5.2]
 [5.5]
 [4.9]
 [5. ]
 [5.5]
 [4.9]
 [4.4]
 [5.1]
 [5. ]
 [4.5]
 [4.4]
 [5. ]
 [5.1]
 [4.8]
 [5.1]
 [4.6]
 [5.3]
 [5. ]
 [7. ]
 [6.4]
 [6.9]
 [5.5]
 [6.5]
 [5.7]
 [6.3]
 [4.9]
 [6.6]
 [5.2]
 [5. ]
 [5.9]
 [6. ]
 [6.1]
 [5.6]
 [6.7]
 [5.6]
 [5.8]
 [6.2]
 [5.6]
 [5.9]
 [6.1]
 [6.3]
 [6.1]
 [6.4]
 [6.6]
 [6.8]
 [6.7]
 [6. ]
 [5.7]
 [5.5]
 [5.5]
 [5.8]
 [6. ]
 [5.4]
 [6. ]
 [6.7]
 [6.3]
 [5.6]
 [5.5]
 [5.5]
 [6.1]
 [5.8]
 [5. ]
 [5.6]
 [5.7]
 [5.7]
 [6.2]
 [5.1]
 [5.7]
 [6.3]
 [5.8]
 [7.1]
 [6.3]
 [6.5]
 [7.6]
 [4.9]
 [7.3]
 [6.7]
 [7.2]
 [6.5]
 [6.4]
 [6.8]
 [5.7]
 [5.8]
 [6.4]
 [6.5]
 [7.7]
 [7.7]
 [6. ]
 [6.9]
 [5.6]
 [7.7]
 [6.3]
 [6.7]
 [7.2]
 [6.2]
 [6.1]
 [6.4]
 [7.2]
 [7.4]
 [7.9]
 [6.4]
 [6.3]
 [6.1]
 [7.7]
 [6.3]
 [6.4]
 [6. ]
 [6.9]
 [6.7]
 [6.

In [42]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(X_train)
print(X_test)

[[4.6]
 [5.7]
 [6.7]
 [4.8]
 [4.4]
 [6.3]
 [6.4]
 [5.2]
 [5. ]
 [5.2]
 [5.8]
 [6. ]
 [6.7]
 [5.4]
 [5.4]
 [5.5]
 [6.3]
 [6.4]
 [6.6]
 [7.2]
 [5.7]
 [7.6]
 [5.6]
 [5.1]
 [7.7]
 [5.8]
 [5.2]
 [5. ]
 [5.1]
 [5. ]
 [6.3]
 [4.8]
 [5. ]
 [5.1]
 [5.6]
 [5.1]
 [5.7]
 [7.7]
 [4.6]
 [6.2]
 [5.7]
 [5.5]
 [6. ]
 [5.8]
 [6. ]
 [5.4]
 [6.2]
 [5.5]
 [5.4]
 [5. ]
 [6.4]
 [5. ]
 [5. ]
 [5.5]
 [6.7]
 [4.9]
 [5.8]
 [5. ]
 [5. ]
 [5.9]
 [5.1]
 [6.9]
 [6. ]
 [6.1]
 [7.7]
 [5.5]
 [4.4]
 [4.3]
 [6. ]
 [7.2]
 [4.6]
 [5.1]
 [4.4]
 [6.3]
 [6.3]
 [4.6]
 [6.8]
 [6.3]
 [4.7]
 [6.1]
 [6.5]
 [6.2]
 [7. ]
 [6.4]
 [5.1]
 [6.9]
 [5.9]
 [6.5]
 [5.7]
 [5.2]
 [6.1]
 [4.5]
 [6.6]
 [5.5]
 [5.3]
 [5.6]
 [7.3]
 [6.7]
 [5.1]
 [4.9]
 [6.7]
 [7.2]
 [4.9]
 [6.7]
 [4.9]
 [6.9]
 [7.4]
 [6.3]
 [5.7]
 [6.5]
 [6.3]
 [6.4]
 [5.6]
 [5.9]
 [5.4]
 [6.1]
 [4.9]
 [5.8]
 [5.8]
 [7.1]]
[[6.1]
 [5.7]
 [7.7]
 [6. ]
 [6.8]
 [5.4]
 [5.6]
 [6.9]
 [6.2]
 [5.8]
 [6.5]
 [4.8]
 [5.5]
 [4.9]
 [5.1]
 [6.3]
 [6.5]
 [5.6]
 [5.7]
 [6.4]
 [4.7]
 [6.1]
 [5. 

In [44]:
model = LinearRegression()

In [45]:
model.fit(X_train, y_train)


LinearRegression()

In [47]:
y_pred = model.predict(X_test)
print(y_pred)

[1.21137342 0.90919794 2.42007535 1.13582955 1.74018051 0.68256633
 0.83365407 1.81572438 1.28691729 0.98474181 1.5135489  0.22930311
 0.7581102  0.30484698 0.45593472 1.36246116 1.5135489  0.83365407
 0.90919794 1.43800503 0.15375924 1.21137342 0.38039085 1.43800503
 2.57116309 1.66463664 1.66463664 1.74018051 0.22930311 0.22930311]


In [48]:
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 0.1979546681395589


In [49]:
r2 = r2_score(y_test, y_pred)
print(f"R-squared: {r2}")

R-squared: 0.7167580265093751
